name: Send emails daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Write config
        run: |
          mkdir -p config
          cat > config/custom.yaml <<'EOF'
          zotero:
            user_id: ${oc.env:ZOTERO_ID}
            api_key: ${oc.env:ZOTERO_KEY}
            include_path: null

          email:
            sender: ${oc.env:SENDER}
            receiver: ${oc.env:RECEIVER}
            smtp_server: smtp.qq.com
            smtp_port: 465
            sender_password: ${oc.env:SENDER_PASSWORD}

          llm:
            api:
              key: ${oc.env:OPENAI_API_KEY}
              base_url: ${oc.env:OPENAI_API_BASE}
            generation_kwargs:
              model: Qwen/Qwen3.5-27B
            language: Chinese

          source:
            arxiv:
              category: ["cs.LG", "cond-mat.mtrl-sci", "physics.chem-ph", "cs.AI", "q-bio.BM"]
              include_cross_list: false

          executor:
            debug: ${oc.env:DEBUG,null}
            send_empty: true
            source: ['arxiv']
          EOF
          echo "Use custom config:"
          cat config/custom.yaml

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        run: uv run src/zotero_arxiv_daily/main.py
